name: Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: public
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
